defmodule PtcRunner.Kernel.LLMFailureCatalog do
  @moduledoc """
  Closed catalog of admitted LLM provider, model-alias protocol, and
  whole-request timeout failures.

  `PtcRunner.Kernel.ProviderError` and `PtcRunner.Kernel.SafeMetadata` consume
  this module. `mix ptc.gen_docs` projects the same rows into the generated
  `agent.failure` component. The classifier inspects the existing bounded LLM
  envelope and does not add a field to `tool/llm-request`, `llm/request`,
  inspection, or `run-outcome` maps.

  Authenticated fail-fast consumption stays the provider kinds, Kernel-generated
  provider failures, and whole-request timeout aliases. Model-alias protocol
  reasons are recoverable to `run-outcome` but remain unauthenticated at
  `kernel-llm-provider-failure`.
  """

  @provider_kinds [
    :denied,
    :not_found,
    :unavailable,
    :invalid_request,
    :internal,
    :domain_error,
    :invalid_result,
    :authentication_failed,
    :payment_required,
    :rate_limited,
    :tool_calling_unsupported,
    :usage_unavailable,
    :timeout,
    :transport_error
  ]

  @kernel_provider_reasons [:reservation_bound_exceeded]
  @provider_reasons @provider_kinds ++ @kernel_provider_reasons

  @protocol_reasons [
    :unknown_model_alias,
    :invalid_model_alias,
    :model_alias_required
  ]

  @timeout_reasons [
    :provider_timeout,
    :llm_request_timeout
  ]

  @type provider_kind ::
          :denied
          | :not_found
          | :unavailable
          | :invalid_request
          | :internal
          | :domain_error
          | :invalid_result
          | :authentication_failed
          | :payment_required
          | :rate_limited
          | :tool_calling_unsupported
          | :usage_unavailable
          | :timeout
          | :transport_error

  @type provider_failure_kind :: provider_kind() | :reservation_bound_exceeded

  @spec provider_kinds() :: [provider_kind()]
  def provider_kinds, do: @provider_kinds

  @doc """
  Kebab names SafeMetadata may authenticate as `llm_provider_failure`.

  Includes provider kinds, Kernel-generated provider failures, and whole-request
  timeout aliases. Omits model-alias protocol reasons, which stay unauthenticated
  at fail-fast.
  """
  @spec authenticated_kebabs() :: [String.t()]
  def authenticated_kebabs do
    Enum.uniq(Enum.map(@provider_reasons, &kebab/1) ++ Enum.map(@timeout_reasons, &kebab/1))
  end

  @doc """
  Maps a normalized kebab failure name to the closed consume atom, or `nil`.
  """
  @spec consume_kind(String.t()) :: provider_failure_kind() | nil
  def consume_kind(name) when is_binary(name) do
    cond do
      kebab_in?(name, @timeout_reasons) -> :timeout
      kebab_in?(name, @provider_reasons) -> existing_atom(name)
      true -> nil
    end
  end

  def consume_kind(_name), do: nil

  @doc "PTC-Lisp source for the generated `agent.failure` component."
  @spec lisp_source() :: String.t()
  def lisp_source do
    provider = lisp_or_equals("reason", provider_reason_tokens())
    protocol = lisp_or_equals("reason", protocol_reason_tokens())
    timeout = lisp_or_equals("reason", timeout_reason_tokens())

    """
    (ns agent.failure
      "Closed classification of admitted LLM provider, protocol, and whole-request timeout envelopes."
      {:visibility :discoverable})

    ;; Auto-generated by mix ptc.gen_docs from PtcRunner.Kernel.LLMFailureCatalog.
    ;; Do not edit by hand.

    (defn- named-token [value]
      (cond
        (keyword? value) (name value)
        (string? value) value
        :else nil))

    (defn classify
      "Returns true when `error` is an admitted recoverable LLM envelope.

      Inspects only `kind` and `reason`. Does not add a field to the envelope or
      consume Kernel evidence."
      {:signature "(error :any) -> :bool"}
      [error]
      (and (map? error)
           (let [kind (named-token (get error :kind))
                 reason (named-token (get error :reason))]
             (or (and (or (= kind "provider-error") (= kind "provider_error"))
                      (or #{provider}))
                 (and (or (= kind "protocol-error") (= kind "protocol_error"))
                      (or #{protocol}))
                 (and (= kind "timeout")
                      (or #{timeout}))))))
    """
  end

  defp kebab(atom), do: atom |> Atom.to_string() |> String.replace("_", "-")

  defp provider_reason_tokens, do: Enum.flat_map(@provider_reasons, &spellings/1)
  defp protocol_reason_tokens, do: Enum.flat_map(@protocol_reasons, &spellings/1)
  defp timeout_reason_tokens, do: Enum.flat_map(@timeout_reasons, &spellings/1)

  defp spellings(atom) do
    underscored = Atom.to_string(atom)
    kebab = String.replace(underscored, "_", "-")
    Enum.uniq([kebab, underscored])
  end

  defp kebab_in?(name, atoms), do: name in Enum.map(atoms, &kebab/1)

  defp existing_atom(kebab) do
    kebab |> String.replace("-", "_") |> String.to_existing_atom()
  end

  defp lisp_or_equals(var, tokens) do
    Enum.map_join(tokens, "\n                      ", fn token ->
      ~s|(= #{var} "#{token}")|
    end)
  end
end
