(ns agent.failure
  "Closed classification of admitted LLM provider, protocol, and whole-request timeout envelopes."
  {:visibility :discoverable})

;; Auto-generated by mix ptc.gen_docs from PtcRunner.Kernel.LLMFailureCatalog.
;; Do not edit by hand.

(defn- named-token [value]
  (cond
    (keyword? value) (name value)
    (string? value) value
    :else nil))

(defn classify
  "Returns true when `error` is an admitted recoverable LLM envelope.

  Inspects only `kind` and `reason`. Does not add a field to the envelope or
  consume Kernel evidence."
  {:signature "(error :any) -> :bool"}
  [error]
  (and (map? error)
       (let [kind (named-token (get error :kind))
             reason (named-token (get error :reason))]
         (or (and (or (= kind "provider-error") (= kind "provider_error"))
                  (or (= reason "denied")
                      (= reason "not-found")
                      (= reason "not_found")
                      (= reason "unavailable")
                      (= reason "invalid-request")
                      (= reason "invalid_request")
                      (= reason "internal")
                      (= reason "domain-error")
                      (= reason "domain_error")
                      (= reason "invalid-result")
                      (= reason "invalid_result")
                      (= reason "authentication-failed")
                      (= reason "authentication_failed")
                      (= reason "payment-required")
                      (= reason "payment_required")
                      (= reason "rate-limited")
                      (= reason "rate_limited")
                      (= reason "tool-calling-unsupported")
                      (= reason "tool_calling_unsupported")
                      (= reason "timeout")
                      (= reason "transport-error")
                      (= reason "transport_error")))
             (and (or (= kind "protocol-error") (= kind "protocol_error"))
                  (or (= reason "unknown-model-alias")
                      (= reason "unknown_model_alias")
                      (= reason "invalid-model-alias")
                      (= reason "invalid_model_alias")
                      (= reason "model-alias-required")
                      (= reason "model_alias_required")))
             (and (= kind "timeout")
                  (or (= reason "provider-timeout")
                      (= reason "provider_timeout")
                      (= reason "llm-request-timeout")
                      (= reason "llm_request_timeout")))))))
