name: 'Setup Elixir Environment'
description: 'Install Elixir, OTP, and Mix dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: Set up Elixir
      id: setup-beam
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.19.3'
        otp-version: '28.1'

    - name: Cache deps and _build
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          deps
          _build
          llm_client/deps
          llm_client/_build
          demo/deps
          demo/_build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - name: Get dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        mix deps.get
        cd llm_client && mix deps.get
        cd ../demo && mix deps.get
      shell: bash

    - name: Cache Dialyzer PLT
      uses: actions/cache@v4
      with:
        path: priv/plts
        key: plt-${{ runner.os }}-otp28.1-elixir1.19.3-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          plt-${{ runner.os }}-otp28.1-elixir1.19.3-

    - name: Cache Babashka
      uses: actions/cache@v4
      id: cache-babashka
      with:
        path: _build/tools
        key: babashka-${{ runner.os }}-1.4.192

    - name: Install Babashka
      if: steps.cache-babashka.outputs.cache-hit != 'true'
      run: mix ptc.install_babashka
      shell: bash
