name: 'Setup Claude Code'
description: 'Install Claude Code CLI with caching to avoid installation conflicts'

inputs:
  version:
    description: 'Claude Code version to install (use "latest" for latest)'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether Claude Code was restored from cache'
    value: ${{ steps.cache-claude.outputs.cache-hit }}
  executable-path:
    description: 'Path to Claude Code executable'
    value: ${{ steps.set-output.outputs.executable-path }}

runs:
  using: 'composite'
  steps:
    # Clean up any stale lock files from previous failed installations
    - name: Clean stale lock files
      shell: bash
      run: |
        rm -f /tmp/claude-install.lock 2>/dev/null || true
        rm -f ~/.claude/.installing 2>/dev/null || true

    - name: Cache Claude Code
      id: cache-claude
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.local/bin/claude
          /home/runner/.claude
        # Include week number to bust cache weekly and pick up new versions
        key: claude-code-${{ runner.os }}-v${{ inputs.version }}-week${{ github.run_id }}
        restore-keys: |
          claude-code-${{ runner.os }}-v${{ inputs.version }}-

    - name: Verify cache or install
      id: install
      shell: bash
      run: |
        # Check if binary exists and works (handles stale cache)
        if [ -f /home/runner/.local/bin/claude ] && /home/runner/.local/bin/claude --version >/dev/null 2>&1; then
          echo "Cache valid - Claude Code is working"
          echo "needs_install=false" >> "$GITHUB_OUTPUT"
          /home/runner/.local/bin/claude --version
        else
          echo "Cache invalid or empty - need to install"
          echo "needs_install=true" >> "$GITHUB_OUTPUT"
          # Clean up any partial/corrupted installation
          rm -rf /home/runner/.local/bin/claude /home/runner/.claude 2>/dev/null || true
        fi

    - name: Install Claude Code
      if: steps.install.outputs.needs_install == 'true'
      shell: bash
      run: |
        echo "Installing Claude Code..."
        for attempt in 1 2 3; do
          echo "Installation attempt $attempt..."
          rm -f /tmp/claude-install.lock 2>/dev/null || true
          rm -f ~/.claude/.installing 2>/dev/null || true
          if curl -fsSL https://claude.ai/install.sh | bash; then
            echo "Claude Code installed successfully"
            /home/runner/.local/bin/claude --version
            break
          fi
          if [ $attempt -eq 3 ]; then
            echo "Failed to install Claude Code after 3 attempts"
            exit 1
          fi
          echo "Installation failed, retrying in 5s..."
          sleep 5
        done

    - name: Add Claude Code to PATH
      shell: bash
      run: echo "/home/runner/.local/bin" >> "$GITHUB_PATH"

    - name: Set outputs
      id: set-output
      shell: bash
      run: |
        echo "executable-path=/home/runner/.local/bin/claude" >> "$GITHUB_OUTPUT"
