defmodule PtcRunner.Session do
  @moduledoc """
  Stateful PTC-Lisp session for embedding applications.

  A session owns only the REPL state that `PtcRunner.Lisp.run/2` already
  understands: explicit `(def ...)` memory and the bounded `*1`/`*2`/`*3`
  turn history. Durable chat messages, user identity, persistence, and tool
  configuration stay with the embedding application. Runtime options can be
  stored as session defaults or passed per evaluation.

  ## Examples

      iex> session = PtcRunner.Session.new(timeout: 1_000)
      iex> {{:ok, step}, session} = PtcRunner.Session.eval(session, "(def x 41)")
      iex> step.memory["x"]
      41
      iex> {{:ok, step}, _session} = PtcRunner.Session.eval(session, "(inc x)")
      iex> step.return
      42

      iex> session = PtcRunner.Session.new(history_depth: 2)
      iex> {{:ok, _}, session} = PtcRunner.Session.eval(session, "1")
      iex> {{:ok, _}, session} = PtcRunner.Session.eval(session, "2")
      iex> {{:ok, step}, _session} = PtcRunner.Session.eval(session, "*1")
      iex> step.return
      2
  """

  alias PtcRunner.Step
  alias PtcRunner.TraceLog
  alias PtcRunner.TraceLog.TurnEvent
  alias PtcRunner.Upstream.Eval, as: UpstreamEval

  @default_history_depth 3

  defstruct memory: %{},
            turn_history: [],
            history_depth: @default_history_depth,
            run_opts: [],
            upstream_runtime: nil,
            session_id: nil,
            turn: 0,
            attempts: 0

  @type t :: %__MODULE__{
          memory: map(),
          turn_history: [term()],
          history_depth: non_neg_integer(),
          run_opts: keyword(),
          upstream_runtime: struct() | pid() | nil,
          session_id: String.t(),
          turn: non_neg_integer(),
          attempts: non_neg_integer()
        }

  @typedoc """
  Result of `eval/3`: the normal `PtcRunner.Lisp.run/2` result paired with the
  session state to use for the next turn.
  """
  @type eval_result :: {{:ok, Step.t()} | {:error, Step.t()}, t()}

  @doc """
  Create a new stateful PTC-Lisp session.

  ## Options

    * `:memory` - initial Lisp memory map (default: `%{}`)
    * `:turn_history` - initial result history, oldest first (default: `[]`)
    * `:history_depth` - maximum stored result count for `*1`, `*2`, `*3`
      references (default: `3`)
    * `:upstream_runtime` - optional `PtcRunner.Upstream.Runtime` handle used
      to evaluate programs through configured upstream MCP/OpenAPI tools
    * `:session_id` - correlation id stamped on this session's turn-log events
      (default: autogenerated). The struct stays a pure value; the id only
      tags emitted turn events so a session's turns can be grouped across a
      trace (plan P2).

  Any other options are stored as default `PtcRunner.Lisp.run/2` options and
  merged with per-eval options.
  """
  @spec new(keyword()) :: t()
  def new(opts \\ []) when is_list(opts) do
    history_depth =
      opts
      |> Keyword.get(:history_depth, @default_history_depth)
      |> normalize_history_depth!()

    {upstream_runtime, opts} = Keyword.pop(opts, :upstream_runtime)
    {session_id, run_opts} = Keyword.pop(opts, :session_id)

    %__MODULE__{
      memory: Keyword.get(run_opts, :memory, %{}),
      turn_history: trim_history(Keyword.get(run_opts, :turn_history, []), history_depth),
      history_depth: history_depth,
      run_opts: Keyword.drop(run_opts, [:memory, :turn_history, :history_depth]),
      upstream_runtime: upstream_runtime,
      session_id: session_id || generate_session_id()
    }
  end

  @doc """
  Evaluate PTC-Lisp source with this session's memory and turn history.

  Session default options and per-call `opts` are passed through to
  `PtcRunner.Lisp.run/2`, then the session's `:memory` and `:turn_history` are
  applied. This lets embedding callers pass normal runtime options such as
  `:tools`, `:context`, `:timeout`, or upstream options while the session
  remains the owner of REPL state. If the session was created with
  `:upstream_runtime`, evaluation goes through `PtcRunner.Upstream.Runtime`.

  On success, the returned session stores `step.memory` and appends
  `step.return` to the bounded history. On error, the returned session is the
  original session, preserving the prior memory and history — but its `attempts`
  counter still advances, since every attempt (including failed ones) is a
  turn-log record.
  """
  @spec eval(t(), String.t(), keyword()) :: eval_result()
  def eval(%__MODULE__{} = session, source, opts \\ [])
      when is_binary(source) and is_list(opts) do
    run_opts =
      session.run_opts
      |> Keyword.merge(opts)
      |> Keyword.put(:memory, session.memory)
      |> Keyword.put(:turn_history, session.turn_history)

    started_at = System.monotonic_time(:millisecond)
    attempt = session.attempts + 1

    case run_lisp(session, source, run_opts) do
      {:ok, %Step{} = step} ->
        updated = %{
          session
          | memory: step.memory,
            turn_history:
              append_history(session.turn_history, step.return, session.history_depth),
            turn: session.turn + 1,
            attempts: attempt
        }

        emit_turn_event(session, updated, source, step, attempt, true, started_at)
        {{:ok, step}, updated}

      {:error, %Step{} = step} ->
        updated = %{session | attempts: attempt}

        emit_turn_event(session, updated, source, step, attempt, false, started_at)
        {{:error, step}, updated}
    end
  end

  # Build and record the canonical turn event (plan P2). Skipped entirely when
  # nothing is recording so the common no-trace path pays nothing.
  defp emit_turn_event(prev, next, source, %Step{} = step, attempt, committed?, started_at) do
    if TraceLog.recording?() do
      %{
        driver: :session,
        session_id: next.session_id,
        turn: next.turn,
        attempt: attempt,
        committed: committed?,
        status: if(committed?, do: :ok, else: :error),
        duration_ms: System.monotonic_time(:millisecond) - started_at,
        program: source,
        result_preview: TurnEvent.preview(step.return),
        prints: step.prints,
        memory_diff: TurnEvent.memory_diff(prev.memory, step.memory),
        tool_calls: tool_call_summaries(step.tool_calls),
        fail: step.fail,
        preludes: prelude_provenance(step.prelude_trace)
      }
      |> TurnEvent.build()
      |> TraceLog.record_turn_event()
    end

    :ok
  end

  defp tool_call_summaries(tool_calls) when is_list(tool_calls) do
    Enum.map(tool_calls, fn call ->
      %{
        "server" => Map.get(call, :server),
        "tool" => Map.get(call, :tool) || Map.get(call, :name),
        "duration_ms" => Map.get(call, :duration_ms),
        "outcome" => if(Map.get(call, :error), do: "error", else: "ok")
      }
    end)
  end

  defp prelude_provenance(%{source_hash: hash, protected_namespaces: namespaces}) do
    [%{"source_hash" => hash, "namespaces" => namespaces}]
  end

  defp prelude_provenance(_), do: []

  defp generate_session_id do
    :crypto.strong_rand_bytes(8) |> Base.encode16(case: :lower)
  end

  defp append_history(history, value, history_depth) do
    trim_history(history ++ [value], history_depth)
  end

  defp trim_history(history, history_depth) when is_list(history) and is_integer(history_depth) do
    history
    |> Enum.take(-max(history_depth, 0))
  end

  defp normalize_history_depth!(depth) when is_integer(depth) and depth >= 0, do: depth

  defp normalize_history_depth!(depth) do
    raise ArgumentError, ":history_depth must be a non-negative integer, got: #{inspect(depth)}"
  end

  defp run_lisp(%__MODULE__{upstream_runtime: nil}, source, opts) do
    PtcRunner.Lisp.run(source, opts)
  end

  defp run_lisp(%__MODULE__{upstream_runtime: runtime}, source, opts) do
    UpstreamEval.run_lisp(runtime, source, opts)
  end
end
